services:
  data-ingestion:
    build: ./ML/data-ingestion
    image: agriguard-data-ingestion:1.0.0
    environment:
      - GCS_BUCKET=agriguard-ac215-data
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/agriguard-dev.json
    volumes:
      - ./ML/data-ingestion/src:/app/src
      - ./ML/data-ingestion/configs:/app/configs
      - ./data:/app/data
      - ./secrets:/app/secrets:ro
    command: python src/download_yield_data.py --start-year 2015 --end-year 2024 --sample

  preprocessing:                       
    build: ./ML/preprocessing         
    image: agriguard-preprocessing:1.0.0
    volumes:
      - ./ML/preprocessing:/app
      - ./data:/app/data
    command: python src/preprocess_data.py

  model-yield-forecasting:
    build: ./ML/model-yield-forecasting
    image: agriguard-yield:1.0.0
    volumes:
      - ./ML/model-yield-forecasting/src:/app/src
      - ./data:/app/data
    command: python src/train_model.py --verbose

  api:
    build: ./ML/api
    image: agriguard-api:0.1.0
    ports:
      - "8000:8000"
    environment:
      - GCS_BUCKET=agriguard-ac215-data
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/agriguard-dev.json
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets:ro
    depends_on:
      - model-yield-forecasting

  workflow:
    build:
      context: .                      
      dockerfile: ML/workflow/Dockerfile
    image: agriguard-workflow:0.1.0
    volumes:
      - ./:/repo
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./secrets:/app/secrets:ro
    working_dir: /repo/ML/workflow
