# Preprocessing Configuration

# Input/Output paths
paths:
  input: "/app/data/raw/yields/iowa_corn_yields_2015_2024.csv"
  output_stress: "/app/data/processed/stress_features"
  output_yield: "/app/data/processed/yield_features"

# Train/validation/test split
data_split:
  train_end_year: 2021
  val_end_year: 2022
  test_start_year: 2023

# Feature engineering
features:
  # Historical yield features
  yield_lags: [1, 2, 3]  # Previous 1, 2, 3 years
  
  # Synthetic satellite features (realistic ranges)
  ndvi:
    early_season_mean: [0.55, 0.75]  # Apr-Jun
    mid_season_mean: [0.75, 0.90]    # Jul-Aug (critical)
    late_season_mean: [0.45, 0.65]   # Sep-Oct
    std_dev: [0.03, 0.10]
  
  sar:
    vv_mean: [-15, -10]  # dB
    vh_mean: [-20, -15]  # dB
    moisture_proxy: [-18, -12]
  
  et:
    seasonal_total: [400, 600]  # mm
    anomaly: [-100, 100]  # mm deviation from normal
  
  gdd:
    cumulative: [2400, 3200]  # Growing degree days
  
  stress:
    days_threshold: [0, 30]  # Days below NDVI threshold
    severity: [0, 1]  # 0=no stress, 1=severe

# Data quality
quality:
  min_yield: 10  # bu/acre
  max_yield: 250  # bu/acre
  min_records_per_county: 3

# Random seed
random_seed: 42
