# Feature Engineering Configuration for AgriGuard

# Historical baseline period
baseline:
  start_year: 2017
  end_year: 2023
  min_samples: 3  # Minimum years of data required

# Growth stages for Iowa corn (day of year)
growth_stages:
  planting:
    start_doy: 120  # May 1
    end_doy: 150    # May 30
  vegetative:
    start_doy: 151  # June 1
    end_doy: 195    # July 14
  reproductive:
    start_doy: 196  # July 15 (VT-R1 tasseling/silking - CRITICAL)
    end_doy: 240    # August 28
  maturity:
    start_doy: 241  # September 1
    end_doy: 273    # September 30

# Critical periods (most yield-sensitive)
critical_periods:
  silking:  # VT-R1 stage
    start_doy: 196
    end_doy: 210
    description: "Tasseling and silking - pollination window"
  grain_fill:  # R2-R4 stage
    start_doy: 211
    end_doy: 240
    description: "Grain fill - determines final yield"

# Anomaly classification thresholds (z-score)
anomaly_thresholds:
  normal:
    min: -1.5
    max: 1.5
  mild:
    min: -2.5
    max: -1.5
    # Also: 1.5 to 2.5
  moderate:
    min: -3.5
    max: -2.5
    # Also: 2.5 to 3.5
  severe:
    min: -999  # Any value below -3.5
    max: -3.5
    # Also: above 3.5

# Persistence windows (days)
persistence_windows: [7, 14, 21, 30]

# Rolling window sizes (days)
rolling_windows:
  short: 7
  medium: 14
  long: 30

# Products and bands to process
products:
  ndvi:
    bands: ['NDVI', 'EVI']
    direction: 'negative'  # Lower = stress
    critical_threshold: 0.5  # Below this = severe stress
  et:
    bands: ['ET', 'PET']
    direction: 'negative'  # Lower = stress
    critical_threshold: 20  # mm (below = water stress)
  lst:
    bands: ['LST_Day', 'LST_Night']
    direction: 'positive'  # Higher = stress
    critical_threshold: 35  # Celsius (above = heat stress)

# Feature engineering settings
features:
  # Aggregation statistics to compute
  aggregations:
    - mean
    - max
    - min
    - std
    - sum
    - median
  
  # Lag periods (days) for temporal features
  lags: [7, 14, 21, 30]
  
  # Difference periods for trend calculation
  diff_periods: [7, 14, 30]
  
  # Interaction terms to create
  interactions:
    - ['ndvi_mean', 'et_mean']  # Drought signature
    - ['lst_max', 'et_mean']    # Heat stress signature
    - ['ndvi_mean', 'lst_max']  # Combined stress

# Data quality settings
quality:
  max_missing_days: 5  # Max consecutive missing days to interpolate
  outlier_threshold: 5.0  # Z-score threshold for outlier removal
  min_valid_samples_per_stage: 10  # Min observations per growth stage

# Output settings
output:
  baselines_path: "processed/baselines"
  anomalies_path: "processed/anomalies"
  features_path: "processed/features"
  file_format: "parquet"
  compression: "snappy"
