[project]
name = "agriguard-workflow"
version = "0.1.0"
description = "Lightweight pipeline orchestrator for AgriGuard MS2"
requires-python = ">=3.11,<3.12"

[tool.uv]
index-url = "https://pypi.org/simple"
