import { Card } from "@/components/ui/card";
import { TrendingUp } from "lucide-react";

interface YieldForecastProps {
  fieldName?: string;
  predictedYield?: number;
  confidenceInterval?: { low: number; high: number };
}

export default function YieldForecast({ 
  fieldName = "North Field Section A",
  predictedYield = 185,
  confidenceInterval = { low: 175, high: 195 }
}: YieldForecastProps) {
  return (
    <Card className="p-6" data-testid="card-yield-forecast">
      <div className="flex items-start justify-between mb-4">
        <div>
          <h3 className="font-semibold">Yield Forecast</h3>
          <p className="text-sm text-muted-foreground">{fieldName}</p>
        </div>
        <TrendingUp className="w-5 h-5 text-primary" />
      </div>
      <div className="space-y-4">
        <div>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-semibold text-primary" data-testid="text-predicted-yield">
              {predictedYield}
            </span>
            <span className="text-lg text-muted-foreground">bu/acre</span>
          </div>
          <p className="text-sm text-muted-foreground mt-1">Predicted yield</p>
        </div>
        <div className="pt-4 border-t">
          <p className="text-sm font-medium mb-2">95% Confidence Interval</p>
          <div className="flex justify-between items-center">
            <div>
              <p className="text-lg font-semibold">{confidenceInterval.low}</p>
              <p className="text-xs text-muted-foreground">Low</p>
            </div>
            <div className="flex-1 mx-4 h-2 bg-muted rounded-full overflow-hidden">
              <div className="h-full bg-primary/50" style={{ width: '70%', marginLeft: '15%' }}></div>
            </div>
            <div>
              <p className="text-lg font-semibold">{confidenceInterval.high}</p>
              <p className="text-xs text-muted-foreground">High</p>
            </div>
          </div>
        </div>
        <p className="text-xs text-muted-foreground pt-2">
          {/* TODO: Replace with actual Vertex AI model name and version */}
          Prediction generated by Vertex AI Yield Model v2.1
        </p>
      </div>
    </Card>
  );
}
