# Yield Forecasting Model Configuration

# Data paths
data:
  input_dir: "/app/data/processed/yield_features"
  output_dir: "/app/data/models/yield_forecaster"

# Model parameters
model:
  type: "xgboost"
  n_estimators: 200
  max_depth: 6
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 3
  gamma: 0.1
  reg_alpha: 0.1
  reg_lambda: 1.0

# Training
training:
  early_stopping_rounds: 20
  eval_metric: "rmse"

# Feature importance
feature_importance:
  top_n: 15

# Random seed
random_seed: 42
