version: '3.8'

services:
  data-ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agriguard-data-ingestion
    volumes:
      - ./config:/config:ro
      - ./secrets:/secrets:ro
      - ./temp:/temp
      - ./logs:/logs
      - C:\Users\artyb\.config\earthengine:/root/.config/earthengine:ro
    environment:
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      # USDA NASS
      - NASS_API_KEY=${NASS_API_KEY}
      # NASA EarthData (new token-based auth)
      - NASA_TOKEN=${NASA_TOKEN}
      # Copernicus (for Sentinel-1 later)
      - COPERNICUS_USER=${COPERNICUS_USER}
      - COPERNICUS_PASSWORD=${COPERNICUS_PASSWORD}
      # Data configuration
      - START_YEAR=${START_YEAR:-2017}
      - START_DATE=${START_DATE}
      - END_DATE=${END_DATE}
      - CORN_YEARS=${CORN_YEARS}
      - PRODUCTS=${PRODUCTS:-ndvi,et,lst}
      - STATE=${STATE:-Iowa}
      - STATE_FIPS=${STATE_FIPS:-19}
      # Processing
      - NUM_WORKERS=${NUM_WORKERS:-4}
      - TEMP_DIR=/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    command: python src/downloaders/gee_modis_downloader.py
